"""The enricher interface layer.

`EnricherInterface` is the abstract base class. There are four implementations, all switchable
by configuration and none removed:
- `DeepSeekEnricher`: the default real implementation, DeepSeek over its OpenAI-compatible API,
  producing semantically real tags.
- `CloudEnricher`: a real implementation using Anthropic Claude (Haiku), also producing
  semantically real tags.
- `MockCloudEnricher`: the mock, returning `mock:`-prefixed fake tags for offline testing and CI.
- `VisionEnricher`: used to evaluate the upload-image path. It sends the image directly to a
  Claude multimodal model and produces a complete card in one step (description, tags and
  extracted_text). It is not the default; the architecture decision is still open.

Contract: in the first three implementations, tags is the only field generated by a cloud
model, this layer is its only source, and there is no rule-based implementation.
VisionEnricher is a candidate replacement for that contract, since it produces ocr_text in the
cloud too. It exists for comparison and does not change the pipeline default.
"""

from .base import EnricherConfigError, EnricherError, EnricherInterface
from .cloud_enricher import CloudEnricher
from .deepseek_enricher import DeepSeekEnricher
from .mock_enricher import MockCloudEnricher
from .vision_enricher import VisionCard, VisionEnricher

__all__ = [
    "EnricherInterface",
    "EnricherError",
    "EnricherConfigError",
    "DeepSeekEnricher",
    "CloudEnricher",
    "MockCloudEnricher",
    "VisionEnricher",
    "VisionCard",
]
