"""The memory card data model.

The fields are fixed and map one-to-one onto the SQLite table:
id, timestamp, trigger_confidence, ocr_text, tags (a JSON array),
raw_image_policy (defaults to "delete"), status (pending or done), created_at, enriched_at.

Everything except tags is produced for free by the system, the OCR or the gatekeeper. tags is
the only field generated by a cloud model.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Optional

from . import config


def utc_now_iso() -> str:
    """The one timestamp format used everywhere: UTC ISO-8601, second precision, with Z."""
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


@dataclass
class MemoryCard:
    """One memory card.

    - `tags` of None means the cloud enricher has not produced them yet, which is the pending
      state. Once produced it is an array of strings, stored as JSON.
    - `enriched_at` is written when tags are backfilled.
    """

    timestamp: str                          # when the frame was grabbed / the trigger fired (ISO)
    trigger_confidence: float               # gatekeeper confidence
    ocr_text: str                           # text from local OCR
    tags: Optional[list[str]] = None        # tags from the cloud; None means not generated yet
    raw_image_policy: str = config.POLICY_DELETE
    status: str = config.STATUS_PENDING
    created_at: str = field(default_factory=utc_now_iso)
    enriched_at: Optional[str] = None
    id: Optional[int] = None                # assigned by SQLite on insert

    def __post_init__(self) -> None:
        if self.raw_image_policy not in config.VALID_RAW_IMAGE_POLICIES:
            raise ValueError(
                f"invalid raw_image_policy: {self.raw_image_policy!r}; "
                f"valid values are {config.VALID_RAW_IMAGE_POLICIES}"
            )
        if self.status not in config.VALID_STATUSES:
            raise ValueError(
                f"invalid status: {self.status!r}; valid values are {config.VALID_STATUSES}"
            )

    # ---- serialisation helpers; tags is JSON text in the database ----
    def tags_json(self) -> Optional[str]:
        return None if self.tags is None else json.dumps(self.tags, ensure_ascii=False)

    @staticmethod
    def tags_from_json(raw: Optional[str]) -> Optional[list[str]]:
        if raw is None:
            return None
        return json.loads(raw)

    def to_row(self) -> dict[str, Any]:
        """Convert to a dict ready to write to SQLite, with tags already JSON-encoded."""
        return {
            "id": self.id,
            "timestamp": self.timestamp,
            "trigger_confidence": self.trigger_confidence,
            "ocr_text": self.ocr_text,
            "tags": self.tags_json(),
            "raw_image_policy": self.raw_image_policy,
            "status": self.status,
            "created_at": self.created_at,
            "enriched_at": self.enriched_at,
        }

    @classmethod
    def from_row(cls, row: Any) -> "MemoryCard":
        """Rebuild from a sqlite3.Row or a dict."""
        d = dict(row)
        return cls(
            id=d["id"],
            timestamp=d["timestamp"],
            trigger_confidence=d["trigger_confidence"],
            ocr_text=d["ocr_text"],
            tags=cls.tags_from_json(d["tags"]),
            raw_image_policy=d["raw_image_policy"],
            status=d["status"],
            created_at=d["created_at"],
            enriched_at=d["enriched_at"],
        )
